# Generated by Django 2.2.6 on 2019-10-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('response', models.CharField(max_length=1)),
                ('reply_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
